- name: Instalar Python 3 y pip
  ansible.builtin.apt:
    name: ["python3", "python3-pip", "python3-venv", "python3-dev", "build-essential"]
    state: present

- name: Instalar passlib para el manejo de contraseñas de Ansible
  ansible.builtin.apt:
    name: python3-passlib
    state: present

- name: Actualizar pip a la última versión
  ansible.builtin.pip:
    name: pip
    state: latest

- name: Instalar Redis server
  ansible.builtin.apt:
    name: redis-server
    state: present

- name: Habilitar y arrancar Redis
  ansible.builtin.service:
    name: redis-server
    state: started
    enabled: yes

- name: Crear entorno virtual para Vote app
  ansible.builtin.command:
    cmd: python3 -m venv /opt/roxs_voting_app/vote/.venv
    creates: /opt/roxs_voting_app/vote/.venv

- name: Asegurar que pip está actualizado en el entorno virtual
  ansible.builtin.pip:
    name: pip
    state: latest
    virtualenv: /opt/roxs_voting_app/vote/.venv

- name: Instalar dependencias en el entorno virtual
  ansible.builtin.pip:
    name:
      - flask==3.0.0
      - redis==5.0.1
      - prometheus_client==0.19.0
      - prometheus_flask_exporter==0.22.4
      - python-dotenv==1.0.0
    virtualenv: /opt/roxs_voting_app/vote/.venv
    state: present

- name: Dar permisos al entorno virtual
  ansible.builtin.file:
    path: /opt/roxs_voting_app/vote/.venv
    recurse: yes
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Crear archivo de entorno Python
  ansible.builtin.copy:
    dest: /opt/roxs_voting_app/vote/.env
    content: |
      FLASK_APP=app.py
      FLASK_ENV=development
      FLASK_DEBUG=1
      FLASK_RUN_HOST=0.0.0.0
      FLASK_RUN_PORT=8080
      REDIS_HOST=localhost
    mode: '0644'
    owner: vagrant
    group: vagrant