- name: Instalar Node.js (versión 20.x, recomendado por NodeSource)
  ansible.builtin.shell: |
    curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
    sudo apt-get install -y nodejs
  args:
    creates: /usr/bin/node